window.archiveLegacy = [
  {date:"2013-07-01",displayDate:"Julio de 2013",category:"Territorio · Sociedad",title:"Pueblo de Mina, pueblo fantasma",subtitle:"Territorio, transformación social y memoria",href:"../Pueblo%20de%20mina.pdf"},
  {date:"2012-04-01",displayDate:"Abril de 2012",category:"Educación · Filosofía",title:"La Eu-ducación",subtitle:"¿La práctica de la Buena Educación?",href:"../La%20Eu-ducacion%20-%20La%20practica%20de%20la%20Buena%20Educacion%20o%20la%20Doctrina%20de%20los%20Aprendizajes.pdf"},
  {date:"2012-03-15",displayDate:"Marzo de 2012",category:"Preescolar · Grafismo",title:"Pre-escolar: arqueología del grafismo",subtitle:"Reflexiones sobre representación y aprendizaje",href:"../Analisis.pdf"},
  {date:"2012-03-01",displayDate:"Marzo de 2012",category:"Evaluación · Educación",title:"El Cuerpo de la Evaluación",subtitle:"Reflexión pedagógica sobre evaluación",href:"../El%20Cuerpo%20de%20la%20Evaluacion.pdf"},
  {date:"2012-02-01",displayDate:"Febrero de 2012",category:"Academia · Trayectoria",title:"Academia JC 10 Años",subtitle:"Memoria de una trayectoria académica",href:"../Academia%20JC%2010%20Anios.pdf"},
  {date:"2011-12-01",displayDate:"Diciembre de 2011",category:"Política educativa · Ciudad",title:"Mega-colegios y otros conceptos",subtitle:"Escuelas ciudadanas, ciudad educadora y ciudadelas educativas",href:"../Mega-colegios,%20Escuelas%20Ciudadanas,%20Ciudad%20Educadora%20y%20Ciudadelas%20Educativas..pdf"},
  {date:"2011-11-01",displayDate:"Noviembre de 2011",category:"Planeación · Educación",title:"El Plan... Es el Camino",subtitle:"Reflexión sobre planificación y acción educativa",href:"../EL%20PLAN...ES%20EL%20CAMINO.pdf"},
  {date:"2011-03-01",displayDate:"Marzo de 2011",category:"Educación · Política pública",title:"El Aporte de los que No CREM",subtitle:"Reflexión sobre política y práctica educativa",href:"../EL%20Aporte%20de%20los%20que%20NO%20CREM.pdf"},
  {date:"2011-02-01",displayDate:"Febrero de 2011",category:"Educación · Realidad",title:"De la Letra a la Realidad",subtitle:"La distancia entre formulación y práctica",href:"../DE%20LA%20LETRA%20A%20LA%20REALIDAD.pdf"},
  {date:"2009-12-01",displayDate:"Diciembre de 2009",category:"Didáctica · Ciencias",title:"Para una clase de ciencias",subtitle:"Reflexiones sobre la enseñanza de las ciencias",href:"../Para%20una%20clase%20de%20ciencias.pdf"},
  {date:"2009-10-01",displayDate:"Octubre de 2009",category:"Docencia · Trabajo",title:"El Maestro Obrero",subtitle:"Una lectura del trabajo docente",href:"../El_Maestro%20Obrero.pdf"},
  {date:"2008-01-01",displayDate:"Enero de 2008",category:"Semiótica · Lenguaje",title:"En un principio era la palabra",subtitle:"Semiótica, representación y significado",href:"../En%20un%20principio%20era%20la%20palabra%20-%20Semiotica.pdf"},
  {date:"2006-11-01",displayDate:"Noviembre de 2006",category:"Cultura · Educación",title:"No hay clases",subtitle:"La cultura detrás de la cultura",href:"../NO%20HAY%20CLASES%20-%20La%20cultura%20detras%20de%20la%20cultura.pdf"},
  {date:"2006-09-01",displayDate:"Septiembre de 2006",category:"Pedagogía · Docencia",title:"Saber y quehacer Pedagógico",subtitle:"Reflexión sobre conocimiento y práctica docente",href:"../Saber%20y%20quehacer%20Pedagogico.pdf"},
  {date:"2006-03-01",displayDate:"Marzo de 2006",category:"Tecnología · Educación",title:"Computadores para educar: ¿Sofisma o realidad?",subtitle:"Tecnología educativa y realidad escolar",href:"../Computadores%20para%20educar%20-%20sofisma%20o%20realidad.pdf"},
  {date:"2005-03-01",displayDate:"Marzo de 2005",category:"Pedagogía · Sistemas",title:"La Clase",subtitle:"Una aproximación desde el enfoque sistémico",href:"../La%20Clase.pdf"}
];