window.archiveLegacy = [
  // Fechas, títulos y clasificación temática conservados según Articulos.htm.
  {sortKey:"2020",year:2020,displayDate:"2020",category:"Literatura y Política",title:"Ponencias - Foro Visión Montelíbano",href:"../Ponencia.pdf"},
  {sortKey:"2015-10",year:2015,displayDate:"Octubre de 2015",category:"Pedagogía y Didáctica",title:"Una Escuela Liberadora",href:"../Una%20Escuela%20Liberadora.pdf",related:[{label:"Plegable en Calaméo",href:"https://en.calameo.com/read/002752003a1a01a61e0e8"}]},
  {sortKey:"2015-09-12",year:2015,displayDate:"12 de septiembre de 2015",category:"Literatura y Política",title:"La región no se muere",href:"../La%20region%20no%20se%20muere.pdf"},
  {sortKey:"2013-10",year:2013,displayDate:"Octubre de 2013",category:"Pedagogía y Didáctica",title:"Buenas Prácticas Educativas",subtitle:"Entrevista",href:"../Calidad%20-%20Entrevistas.pdf"},
  {sortKey:"2013-07",year:2013,displayDate:"Julio de 2013",category:"Pedagogía y Didáctica",title:"Pueblo de Mina, pueblo fantasma",href:"../Pueblo%20de%20mina.pdf"},
  {sortKey:"2013-03",sourceOrder:2,year:2013,displayDate:"Marzo de 2013",category:"Literatura y Política",title:"Cónclave sin clave",href:"../Conclave%20sin%20clave.pdf"},
  {sortKey:"2013-03",sourceOrder:1,year:2013,displayDate:"Marzo de 2013",category:"Literatura y Política",title:"Algunas ideas desde el Sur",href:"../Algunas%20ideas%20sobre%20la%20historia%20desde%20el%20Sur.pdf"},
  {sortKey:"2012-07",year:2012,displayDate:"Julio de 2012",category:"Literatura y Política",title:"Definitivamente Obsceno",href:"../Definitivamente%20Obsceno.pdf"},
  {sortKey:"2012-04",year:2012,displayDate:"Abril de 2012",category:"Pedagogía y Didáctica",title:"La Eu-ducación",subtitle:"¿La práctica de la Buena Educación?",href:"../La%20Eu-ducacion%20-%20La%20practica%20de%20la%20Buena%20Educacion%20o%20la%20Doctrina%20de%20los%20Aprendizajes.pdf"},
  {sortKey:"2012-03",sourceOrder:2,year:2012,displayDate:"Marzo de 2012",category:"Pedagogía y Didáctica",title:"Pre-escolar: arqueología del grafismo",href:"../Analisis.pdf"},
  {sortKey:"2012-03",sourceOrder:1,year:2012,displayDate:"Marzo de 2012",category:"Pedagogía y Didáctica",title:"El Cuerpo de la Evaluación",href:"../El%20Cuerpo%20de%20la%20Evaluacion.pdf"},
  {sortKey:"2012-02",year:2012,displayDate:"Febrero de 2012",category:"Pedagogía y Didáctica",title:"Academia JC 10 Años",href:"../Academia%20JC%2010%20Anios.pdf"},
  {sortKey:"2011-12",year:2011,displayDate:"Diciembre de 2011",category:"Pedagogía y Didáctica",title:"Mega-colegios y otros conceptos",href:"../Mega-colegios,%20Escuelas%20Ciudadanas,%20Ciudad%20Educadora%20y%20Ciudadelas%20Educativas..pdf"},
  {sortKey:"2011-11",year:2011,displayDate:"Noviembre de 2011",category:"Pedagogía y Didáctica",title:"El Plan... Es el Camino",href:"../EL%20PLAN...ES%20EL%20CAMINO.pdf"},
  {sortKey:"2011-10",year:2011,displayDate:"Octubre de 2011",category:"Literatura y Política",title:"Portada y Contraportada del Libro - Los Tres Elefantes",href:"../Libro%20-%20Los%20Tres%20Elefantes.PDF"},
  {sortKey:"2011-08",year:2011,displayDate:"Agosto de 2011",category:"Literatura y Política",title:"Quiero decirte Rebeca",href:"../Quiero%20decirte%20rebeca.pdf"},
  {sortKey:"2011-03",year:2011,displayDate:"Marzo de 2011",category:"Pedagogía y Didáctica",title:"El Aporte de los que No CREM",href:"../EL%20Aporte%20de%20los%20que%20NO%20CREM.pdf"},
  {sortKey:"2011-02",sourceOrder:2,year:2011,displayDate:"Febrero de 2011",category:"Pedagogía y Didáctica",title:"De la Letra a la Realidad",href:"../DE%20LA%20LETRA%20A%20LA%20REALIDAD.pdf"},
  {sortKey:"2011-02",sourceOrder:1,year:2011,displayDate:"Febrero de 2011",category:"Literatura y Política",title:"El último de mis seres imaginarios",href:"https://www.letralia.com/247/especial02.htm"},
  {sortKey:"2009-12",year:2009,displayDate:"Diciembre de 2009",category:"Pedagogía y Didáctica",title:"Para una clase de ciencias",href:"../Para%20una%20clase%20de%20ciencias.pdf"},
  {sortKey:"2009-10",year:2009,displayDate:"Octubre de 2009",category:"Pedagogía y Didáctica",title:"El Maestro Obrero",href:"../El_Maestro%20Obrero.pdf"},
  {sortKey:"2008-01",year:2008,displayDate:"Enero de 2008",category:"Pedagogía y Didáctica",title:"En un principio era la palabra",subtitle:"Semiótica",href:"../En%20un%20principio%20era%20la%20palabra%20-%20Semiotica.pdf"},
  {sortKey:"2006-11",sourceOrder:2,year:2006,displayDate:"Noviembre de 2006",category:"Pedagogía y Didáctica",title:"No hay clases",subtitle:"La cultura detrás de la cultura",href:"../NO%20HAY%20CLASES%20-%20La%20cultura%20detras%20de%20la%20cultura.pdf"},
  {sortKey:"2006-11",sourceOrder:1,year:2006,displayDate:"Noviembre de 2006",category:"Literatura y Política",title:"Fiestas en Corralejas",href:"../Fiestas%20en%20Corralejas.pdf"},
  {sortKey:"2006-09",year:2006,displayDate:"Septiembre de 2006",category:"Pedagogía y Didáctica",title:"Saber y quehacer Pedagógico",href:"../Saber%20y%20quehacer%20Pedagogico.pdf"},
  {sortKey:"2006-03",sourceOrder:2,year:2006,displayDate:"Marzo de 2006",category:"Pedagogía y Didáctica",title:"Computadores para educar",subtitle:"¿Sofisma o realidad?",href:"../Computadores%20para%20educar%20-%20sofisma%20o%20realidad.pdf"},
  {sortKey:"2006-02",year:2006,displayDate:"Febrero de 2006",category:"Literatura y Política",title:"Qué tan artificial es la inteligencia",href:"../Que%20tan%20artificial%20es%20la%20inteligencia.pdf"},
  {sortKey:"2005-03",year:2005,displayDate:"Marzo de 2005",category:"Pedagogía y Didáctica",title:"La Clase",subtitle:"Una aproximación desde el enfoque sistémico",href:"../La%20Clase.pdf"},

  {sortKey:"0000",year:null,displayDate:"Sin fecha indicada",category:"Pedagogía y Didáctica",title:"Representaciones Semióticas en la Aprehensión y Comprensión de los Objetos",href:"https://www.calameo.com/books/002752003818976a3adfc"},
  {sortKey:"0000",year:null,displayDate:"Sin fecha indicada",category:"Pedagogía y Didáctica · Literatura y Política",title:"Calidad educativa o Buena Educación",subtitle:"También aparece en la sección Literatura y Política como «El Culebrón de la Calidad Educativa»",href:"../Calidad%20Educativa%20o%20Buena%20Educacion.pdf"},
  {sortKey:"0000",year:null,displayDate:"Sin fecha indicada",category:"Pedagogía y Didáctica",title:"Yo Maestro/Investigador",subtitle:"Notas",href:"../Tarea.pdf"},
  {sortKey:"0000",year:null,displayDate:"Sin fecha indicada",category:"Pedagogía y Didáctica",title:"Modelación",href:"../Modelacion.pdf"},
  {sortKey:"0000",year:null,displayDate:"Sin fecha indicada",category:"Pedagogía y Didáctica",title:"Enseñanza y Pensamiento Espacial",href:"../Ensenanza%20y%20pensamiento.pdf"},
  {sortKey:"0000",year:null,displayDate:"Sin fecha indicada",category:"Literatura y Política",title:"Diomedes Díaz",href:"../Diomedes%20Diaz.pdf"},
  {sortKey:"0000",year:null,displayDate:"Sin fecha indicada",category:"Literatura y Política",title:"Formato Único de Hoja de Vida",href:"../Hoja%20de%20Vida%20Formato%20unico-%20Jorge%20Cotera.pdf"},
  {sortKey:"0000",year:null,displayDate:"Sin fecha indicada",category:"Literatura y Política",title:"Cómo pensar en alternativas para un nuevo orden social",href:"../Como%20pensar%20en%20alternativas%20para%20un%20nuevo%20orden%20social%20en%20medio%20de%20Conflictos%20de%20Intereses.pdf",related:[{label:"Plegable en Calaméo",href:"https://en.calameo.com/read/002752003e0deafa6c82e"}]},
  {sortKey:"0000",year:null,displayDate:"Sin fecha indicada",category:"Literatura y Política",title:"Tres Símbolos",href:"../Tres%20Simbolos.pdf"},
  {sortKey:"0000",year:null,displayDate:"Sin fecha indicada",category:"Literatura y Política",title:"Bases para el Foro Educativo",href:"../Euducacion.pdf"}
];
