window.libraryContent = [
  {category:"Pedagogía y lenguaje",title:"Enfoque Metodológico Textual",href:"../Enfoque%20Metodologico.pdf",type:"PDF"},
  {category:"Pedagogía y lenguaje",title:"Aproximación al texto escrito",href:"../Aproximacion%20al%20texto%20escrito.pdf",type:"PDF"},
  {category:"Matemáticas",title:"Proporción Áurea",href:"../Aurea.pdf",type:"PDF"},
  {category:"Semiótica y lenguaje",title:"El signo y el texto",href:"../El%20Signo%20y%20el%20Texto.pdf",type:"PDF"},
  {category:"Competencias",title:"Devenir de las Competencias",href:"../Devenir%20de%20las%20Competecias.pdf",type:"PDF"},
  {category:"Competencias",title:"Competencia, Capacidad, Habilidad y Destrezas",href:"../Competencia,%20Capacidad,%20Habilidad%20y%20Destrezas.pdf",type:"PDF"},
  {category:"Semiótica y lenguaje",title:"Signo y Significación",href:"../Signo%20y%20Significacion.pdf",type:"PDF"},
  {category:"Pedagogía",title:"Pedagogía - Kant",href:"../Pedagogia%20-%20Kant.pdf",type:"PDF"},
  {category:"Lenguaje",title:"Psicogénesis de la Lengua Escrita",href:"../Psicogenesis%20de%20la%20Lengua%20Escrita.pdf",type:"PDF"},
  {category:"Evaluación",title:"Objeto de Evaluación",href:"../Objeto%20de%20Evaluacion.pdf",type:"PDF"},
  {category:"Evaluación",title:"La posición del MEN respecto a informes, logros e indicadores",href:"../Informes.pdf",type:"PDF"},
  {category:"Educación matemática",title:"Lineamientos curriculares de Matemáticas",href:"../04.%20%20Matematicas.pdf",type:"PDF"},
  {category:"Educación matemática",title:"Estándares de Competencia en Educación Matemática",href:"../EstndaresMatemtica2007.pdf",type:"PDF"},
  {category:"Educación matemática",title:"Fundamentos de Educación Matemática del ICFES",href:"../MATEMATICA%20(Fundamentos%20de%20la%20prueba).pdf",type:"PDF"},
  {category:"Educación matemática",title:"Evolución Histórica y Epistemológica de la Educación Matemática en Colombia",href:"../Los%20Lineamientos%20de%20Educacion%20Matematica%20como%20Evolucion%20Historica.pdf",type:"PDF"},
  {category:"Ciencias naturales",title:"Lineamientos Curriculares de Ciencias Naturales",href:"../07.%20%20Ciencias%20naturales.pdf",type:"PDF"},
  {category:"Ciencias naturales",title:"Estándares de Ciencias Naturales y Sociales",href:"../Estandares%20Basicos%20por%20Competencias%20en%20Ciencias%20Naturales%20y%20Socieles.pdf",type:"PDF"},
  {category:"Ciencias naturales",title:"Fundamentos de Ciencias Naturales del ICFES",href:"../Fundamentos%20de%20Ciencias%20Naturales-Icfes.pdf",type:"PDF"},
  {category:"Lenguaje",title:"Lineamientos Curriculares de Lenguaje",href:"../03.%20%20Lengua%20castellana.pdf",type:"PDF"},
  {category:"Lenguaje",title:"Estándares Básicos por Competencias en Lenguaje",href:"../Estandares%20Basicos%20por%20Competencias%20en%20Lenguaje.pdf",type:"PDF"},
  {category:"Lenguaje",title:"Fundamentos de Lenguaje del ICFES",href:"../LENGUAJE%20(Fundamentos).pdf",type:"PDF"},
  {category:"Ética",title:"Lineamientos Curriculares de Ética",href:"../06.%20%20Etica.pdf",type:"PDF"},
  {category:"Educación artística",title:"Lineamientos Curriculares de Artística",href:"../11.%20%20Educacion%20artistica.pdf",type:"PDF"},
  {category:"Educación física",title:"Lineamientos Curriculares de Educación Física",href:"../09.%20%20Educacion%20fisica%20recreacion%20y%20deportes.pdf",type:"PDF"},
  {category:"Lengua extranjera",title:"Estándares Básicos por Competencias en Lengua Extranjera - Inglés",href:"../Estandares%20Basicos%20por%20Competencias%20en%20Lengua%20Extragera-%20Ingles.pdf",type:"PDF"}
];
