window.libraryContent = [
  {category:"Pedagogía y lenguaje",title:"Enfoque Metodológico Textual",href:"../Enfoque%20Metodologico.pdf",type:"PDF"},
  {category:"Pedagogía y lenguaje",title:"Aproximación al texto escrito",href:"../Aproximacion%20al%20texto%20escrito.pdf",type:"PDF"},
  {category:"Matemáticas",title:"Proporción Áurea",href:"../Aurea.pdf",type:"PDF"},
  {category:"Semiótica y lenguaje",title:"El signo y el texto",href:"../El%20Signo%20y%20el%20Texto.pdf",type:"PDF"},
  {category:"Competencias",title:"Devenir de las Competencias",href:"../Devenir%20de%20las%20Competecias.pdf",type:"PDF"},
  {category:"Competencias",title:"Competencia, Capacidad, Habilidad y Destrezas",href:"../Competencia,%20Capacidad,%20Habilidad%20y%20Destrezas.pdf",type:"PDF"},
  {category:"Semiótica y lenguaje",title:"Signo y Significación",href:"../Signo%20y%20Significacion.pdf",type:"PDF"},
  {category:"Ciencias naturales",title:"Exposición Origen de la Vida",href:"../Origen%20de%20la%20vida.pdf",type:"PDF"},
  {category:"Ciencias naturales",title:"Exposición Teoría Celular",href:"../Exposicion%20Teoria%20Celular.pdf",type:"PDF"},
  {category:"Ciencias naturales",title:"El Universo",href:"../Universo.pdf",type:"PDF"},
  {category:"Pedagogía",title:"Pedagogía - Kant",href:"../Pedagogia%20-%20Kant.pdf",type:"PDF"},
  {category:"Lenguaje",title:"Psicogénesis de la Lengua Escrita",href:"../Psicogenesis%20de%20la%20Lengua%20Escrita.pdf",type:"PDF"},
  {category:"Evaluación",title:"Objeto de Evaluación",href:"../Objeto%20de%20Evaluacion.pdf",type:"PDF"},
  {category:"Psicología y aprendizaje",title:"Wetheimer y la experiencia de los monos",href:"../Wetheimer%20y%20la%20experiencia%20de%20los%20monos.pdf",type:"PDF"},
  {category:"Lenguaje",title:"Raíces Griegas y latinas",href:"../Raices%20Griegas%20y%20latinas.pdf",type:"PDF"},
  {category:"Evaluación",title:"La posición del MEN respecto a informes, logros e indicadores",href:"../Informes.pdf",type:"PDF"},

  {category:"Educación matemática",title:"Lineamientos curriculares de Matemáticas",href:"../04.%20%20Matematicas.pdf",type:"PDF"},
  {category:"Educación matemática",title:"Estándares de Competencia en Educación Matemática",href:"../EstndaresMatemtica2007.pdf",type:"PDF"},
  {category:"Educación matemática",title:"Fundamentos de Educación Matemática del ICFES",href:"../MATEMATICA%20(Fundamentos%20de%20la%20prueba).pdf",type:"PDF"},
  {category:"Educación matemática",title:"Evolución Histórica y Epistemológica de la Educación Matemática en Colombia",href:"../Los%20Lineamientos%20de%20Educacion%20Matematica%20como%20Evolucion%20Historica.pdf",type:"PDF"},
  {category:"Ciencias naturales",title:"Lineamientos Curriculares de Ciencias Naturales",href:"../07.%20%20Ciencias%20naturales.pdf",type:"PDF"},
  {category:"Ciencias naturales",title:"Estándares de Ciencias Naturales y Sociales",href:"../Estandares%20Basicos%20por%20Competencias%20en%20Ciencias%20Naturales%20y%20Socieles.pdf",type:"PDF"},
  {category:"Ciencias naturales",title:"Fundamentos de Ciencias Naturales del ICFES",href:"../Fundamentos%20de%20Ciencias%20Naturales-Icfes.pdf",type:"PDF"},
  {category:"Lenguaje",title:"Lineamientos Curriculares de Lenguaje",href:"../03.%20%20Lengua%20castellana.pdf",type:"PDF"},
  {category:"Lenguaje",title:"Estándares Básicos por Competencias en Lenguaje",href:"../Estandares%20Basicos%20por%20Competencias%20en%20Lenguaje.pdf",type:"PDF"},
  {category:"Lenguaje",title:"Fundamentos de Lenguaje del ICFES",href:"../LENGUAJE%20(Fundamentos).pdf",type:"PDF"},
  {category:"Ética",title:"Lineamientos Curriculares de Ética",href:"../06.%20%20Etica.pdf",type:"PDF"},
  {category:"Educación artística",title:"Lineamientos Curriculares de Artística",href:"../11.%20%20Educacion%20artistica.pdf",type:"PDF"},
  {category:"Educación física",title:"Lineamientos Curriculares de Educación Física",href:"../09.%20%20Educacion%20fisica%20recreacion%20y%20deportes.pdf",type:"PDF"},
  {category:"Lengua extranjera",title:"Estándares Básicos por Competencias en Lengua Extranjera - Inglés",href:"../Estandares%20Basicos%20por%20Competencias%20en%20Lengua%20Extragera-%20Ingles.pdf",type:"PDF"},
  {category:"Preescolar",title:"Lineamientos de Pre-escolar",href:"../02.%20%20Preescolar.pdf",type:"PDF"},

  {category:"Evaluación",title:"Instrumento para Diagnóstico de Estudiantes",href:"../Instrumnto%20para%20Diagnostico%20con%20los%20Estudiantes.pdf",type:"PDF"},
  {category:"Currículo y planeación",title:"Formato para Organizar los Ejes",href:"../Ejes%20Curriculares%20-%25.xltx",type:"XLTX"},
  {category:"Evaluación",title:"Modelo de informe por Observaciones y sugerencias",href:"../Observaciones%20y%20sugerencias.pdf",type:"PDF"},
  {category:"Evaluación",title:"Modelo de rúbrica solicitado por algunos docentes",href:"../Rubrica.pdf",type:"PDF"},
  {category:"Currículo y planeación",title:"Maya - Plan de Periodo",href:"../MAYA%20PLANES%20DE%20PERIODO.pdf",type:"PDF"},
  {category:"Currículo y planeación",title:"Maya - Plan de Clases",href:"../MAYA%20PLANES%20DE%20CLASES%20-%20AREA.pdf",type:"PDF"},
  {category:"Currículo y planeación",title:"Cómo planear con las Mayas",href:"../Como%20planear%20con%20las%20Mayas.pdf",type:"PDF"},
  {category:"Didáctica",title:"Ejemplo de Guías de Intervención",href:"../GUIAS%20PARA%20GRADO%20PRIMERO%20(CIENCIAS%20NATURALES).pdf",type:"PDF"},
  {category:"Currículo y planeación",title:"Ejemplo de Plan de Área",href:"../Plan%20de%20Área%20de%20Matemática%20en%20Cosntrucción.pdf",type:"PDF"},
  {category:"Evaluación",title:"Formato para la Auto-evalución del Área",href:"../Formato%20para%20la%20Autoevalucion%20del%20Area.pdf",type:"PDF"},
  {category:"Pensamiento crítico",title:"Imágenes",href:"../Imagenes.pdf",type:"PDF"},
  {category:"Pensamiento crítico",title:"Puntos",href:"../Puntos.pdf",type:"PDF"},
  {category:"Pensamiento crítico",title:"Foro",href:"../Foro.pdf",type:"PDF"},
  {category:"Pensamiento crítico",title:"Políticas Públicas en el contexto Sanjorgino",href:"../Politicas%20Publicas%20en%20Educacion%20-%20Prespectiva%20Critica.pdf",type:"PDF"},
  {category:"Pensamiento crítico",title:"¿Por qué hoy no es posible la revolución?",href:"http://elpais.com/elpais/2014/09/22/opinion/1411396771_691913.html",type:"WEB",external:true}
];
