window.siteSearchStatic = window.siteSearchStatic || [];
window.siteSearchStatic.push(
  {type:"Sección",title:"Secretaría de Educación de Montelíbano",description:"Archivo histórico 2012–2015 con buenas prácticas, sexualidad e ideograma institucional.",href:"secretaria-educacion.html",keywords:"Secretaría Educación Montelíbano gestión educativa 2012 2013 2014 2015 buenas prácticas sexualidad ideograma"},
  {type:"Sección",title:"Fundación San Isidro",description:"Acompañamiento regional, Ruta de la Calidad, autoevaluación y planes de mejoramiento.",href:"fundacion-san-isidro.html",keywords:"Fundación San Isidro Cerro Matoso educación pública región Ruta Calidad autoevaluación PEI planes estudio mejoramiento 2012"},
  {type:"Sección",title:"CESUM",description:"Acompañamiento a la gestión académica, evaluación, Pruebas Saber y mejoramiento institucional.",href:"cesum.html",keywords:"CESUM Concentración Educativa del Sur Montelíbano gestión académica pruebas objetivas sistema evaluación Saber mejoramiento 2011 2012 2013 2014"},
  {type:"Sección",title:"Colegio El Rosario",description:"Archivo del área de Matemáticas para 9.º, 10.º y 11.º con evaluación y seguimiento.",href:"rosario.html",keywords:"Colegio El Rosario FEDIMON Montelíbano matemáticas noveno décimo undécimo evaluación rúbrica observaciones sugerencias"},
  {type:"Sección",title:"Puerto Libertador",description:"Memoria de acompañamiento institucional, planes de mejoramiento y formación docente en didáctica.",href:"puerto-libertador.html",keywords:"Puerto Libertador PEI plan mejoramiento didáctica matemáticas lengua formación docente Calixto Acosta Tomás Arévalo"},
  {type:"Sección",title:"San José de Uré",description:"Memoria territorial sobre cultura, currículo, formación docente y evaluación en 2010.",href:"ure.html",keywords:"San José de Uré Ure territorio cultura palenque currículo archivo pedagógico evaluación pruebas objetivas 2010 Fundación San Isidro"},
  {type:"Sección",title:"Institución Educativa San Bernardo",description:"Acompañamiento académico a estudiantes de grado undécimo alrededor de la Prueba Saber en 2012.",href:"san-bernardo.html",keywords:"San Bernardo Montelíbano 2012 grado undécimo prueba Saber acompañamiento académico padres familia Academia JC"},
  {type:"Sección",title:"La Apartada",description:"Acompañamiento curricular 2009–2010: evaluación institucional, mejoramiento, didáctica y planes de estudio.",href:"la-apartada.html",keywords:"La Apartada 2009 2010 currículo evaluación institucional autoevaluación heteroevaluación plan mejoramiento INDAPAZ LUISFERGOB didáctica situaciones problema"},

  {type:"Recurso",title:"Buenas Prácticas",description:"Documento del archivo histórico de la Secretaría de Educación de Montelíbano.",href:"../Buenas%20Practicas.pdf",keywords:"Secretaría Educación buenas prácticas gestión educativa Montelíbano"},
  {type:"Recurso",title:"Sexualidad",description:"Material histórico asociado al trabajo educativo de la Secretaría de Educación.",href:"../Sexualidad.pdf",keywords:"Secretaría Educación sexualidad formación Montelíbano"},
  {type:"Recurso",title:"Ideograma de la Secretaría de Educación",description:"Representación gráfica conservada en el archivo institucional.",href:"../Secretaria%20de%20Educacion%20-%20Mapa.pdf",keywords:"Secretaría Educación mapa ideograma organización Montelíbano"},
  {type:"Recurso",title:"Plan de Mejoramiento - José María Córdoba, Pica-Pica Nuevo",description:"Evidencia histórica del acompañamiento regional asociado a Fundación San Isidro.",href:"../Plan%20de%20Mejoramiento%20-%202011-Jose%20Maria%20Cordoba%20-%20Pica%20Pica%20Nuevo.pdf",keywords:"Fundación San Isidro plan mejoramiento José María Córdoba Pica Pica Montelíbano"},
  {type:"Recurso",title:"Plan de Mejoramiento - José María Córdoba, Puerto Libertador",description:"Evidencia histórica del acompañamiento regional asociado a Fundación San Isidro.",href:"../Plan%20de%20Mejoramiento%20-%202011-Jose%20Maria%20Cordoba%20-%20Pto%20Libertador.pdf",keywords:"Fundación San Isidro plan mejoramiento José María Córdoba Puerto Libertador"},
  {type:"Recurso",title:"Plan de Mejoramiento - La Esperanza, Parcelas de San Javier",description:"Evidencia histórica del acompañamiento regional asociado a Fundación San Isidro.",href:"../Plan%20de%20Mejoramiento%20-%202011-La%20Esperanza%20de%20Parcelas%20de%20San%20javier.pdf",keywords:"Fundación San Isidro plan mejoramiento La Esperanza Parcelas San Javier Montelíbano"},
  {type:"Recurso",title:"Plan de Mejoramiento - Germán Gómez Peláez",description:"Evidencia histórica del acompañamiento regional asociado a Fundación San Isidro.",href:"../Plan%20de%20Mejoramiento%20-%202011%20-%20German%20Gomez%20Pelaez.pdf",keywords:"Fundación San Isidro plan mejoramiento Germán Gómez Peláez Puerto Libertador"},
  {type:"Recurso",title:"Plan de Mejoramiento - Sitio Nuevo, La Apartada",description:"Evidencia histórica del acompañamiento regional asociado a Fundación San Isidro.",href:"../Plan%20de%20Mejoramiento%20-%202011-Sitio%20Nuevo%20-%20La%20Apartada.pdf",keywords:"Fundación San Isidro plan mejoramiento Sitio Nuevo La Apartada"},

  {type:"Recurso",title:"Análisis histórico CESUM",description:"Documento de análisis conservado en el archivo institucional de CESUM.",href:"../Analisis%20Cesum.pdf",keywords:"CESUM análisis histórico evaluación Montelíbano"},
  {type:"Recurso",title:"Saber General",description:"Documento de referencia municipal enlazado desde CESUM.",href:"../Saber%20General.pdf",keywords:"CESUM Saber General municipio pruebas resultados"},
  {type:"Recurso",title:"CESUM 2015",description:"Documento institucional correspondiente al archivo de 2015.",href:"../Cesum.pdf",keywords:"CESUM 2015 institución evaluación"},
  {type:"Recurso",title:"Resumen de Categorías ICFES",description:"Material de análisis asociado a resultados y categorías.",href:"../Resumen%20Categorias.pdf",keywords:"CESUM ICFES categorías análisis resultados"},
  {type:"Recurso",title:"Categorías emergentes",description:"Ejemplo de organización de categorías conservado en CESUM.",href:"../Categorias%20Emergentes.pdf",keywords:"CESUM categorías emergentes análisis"},
  {type:"Recurso",title:"Día E 2016",description:"Informe enlazado desde el archivo institucional de CESUM.",href:"../Informes%202016.pdf",keywords:"CESUM Día E 2016 informe"},

  {type:"Recurso",title:"Criterios para la evaluación - El Rosario",description:"Documento general del área de Matemáticas del Colegio El Rosario.",href:"../Criterios%20del%20area.pdf",keywords:"Rosario matemáticas criterios evaluación"},
  {type:"Recurso",title:"Rúbrica de exposiciones - El Rosario",description:"Instrumento de valoración utilizado en el área de Matemáticas.",href:"../Rubrica.pdf",keywords:"Rosario rúbrica exposiciones evaluación"},
  {type:"Recurso",title:"Observaciones y sugerencias - El Rosario",description:"Documento de seguimiento del archivo de Matemáticas.",href:"../Observaciones%20y%20sugerencias.pdf",keywords:"Rosario observaciones sugerencias seguimiento matemáticas"},
  {type:"Recurso",title:"Taller de Didáctica de las Matemáticas - Puerto Libertador",description:"Registro audiovisual enlazado desde la memoria territorial de Puerto Libertador.",href:"https://www.youtube.com/watch?v=gRYfDMb6ZF0",keywords:"Puerto Libertador didáctica matemáticas taller docentes básica primaria video"},

  {type:"Recurso",title:"Plan de Mejoramiento INDAPAZ",description:"Documento histórico del acompañamiento curricular en La Apartada.",href:"../Plan_de_Mejoramiento_INDAPAZ.pdf",keywords:"La Apartada INDAPAZ plan mejoramiento currículo"},
  {type:"Recurso",title:"Plan de Mejoramiento LUISFERGOB",description:"Documento histórico del acompañamiento curricular en La Apartada.",href:"../Plan%20de%20Mejoramiento%20LUISFERGOB.pdf",keywords:"La Apartada LUISFERGOB plan mejoramiento currículo"},
  {type:"Recurso",title:"Sistema institucional de evaluación LUISFERGOB",description:"Documento histórico del proceso de evaluación institucional en La Apartada.",href:"../SISTEMA%20DE%20EVALUACION%20LUISFERGOB.pdf",keywords:"La Apartada LUISFERGOB sistema evaluación institucional"},
  {type:"Recurso",title:"Informe general La Apartada 2009",description:"Informe del primer año del acompañamiento curricular documentado.",href:"../INFORMES%20LA%20APARTADA%202009.pdf",keywords:"La Apartada informe 2009 currículo evaluación mejoramiento"},
  {type:"Recurso",title:"Informe general La Apartada 2010",description:"Informe del segundo año del acompañamiento curricular documentado.",href:"../INFORMES%20LA%20APARTADA%202010.pdf",keywords:"La Apartada informe 2010 currículo evaluación mejoramiento"},
  {type:"Recurso",title:"Malla de planeación por períodos INDAPAZ",description:"Herramienta histórica de organización curricular de La Apartada.",href:"../MAYA%20PLAN%20DE%20PERIODO%20-%20INDAPAZ.pdf",keywords:"La Apartada INDAPAZ malla planeación periodos plan estudio"},
  {type:"Recurso",title:"Malla de planeación por períodos LUISFERGOB",description:"Herramienta histórica de organización curricular de La Apartada.",href:"../MAYA%20PLAN%20DE%20PERIODO%20-%20LUISFERGOB.pdf",keywords:"La Apartada LUISFERGOB malla planeación periodos plan estudio"}
);
