window.siteSearchStatic = window.siteSearchStatic || [];
window.siteSearchStatic.push(
  {type:"Sección",title:"Secretaría de Educación de Montelíbano",description:"Archivo histórico 2012–2015 con buenas prácticas, sexualidad e ideograma institucional.",href:"secretaria-educacion.html",keywords:"Secretaría Educación Montelíbano gestión educativa 2012 2013 2014 2015 buenas prácticas sexualidad ideograma"},
  {type:"Sección",title:"Fundación San Isidro",description:"Acompañamiento regional, Ruta de la Calidad, autoevaluación y planes de mejoramiento.",href:"fundacion-san-isidro.html",keywords:"Fundación San Isidro Cerro Matoso educación pública región Ruta Calidad autoevaluación PEI planes estudio mejoramiento 2012"},

  {type:"Recurso",title:"Buenas Prácticas",description:"Documento del archivo histórico de la Secretaría de Educación de Montelíbano.",href:"../Buenas%20Practicas.pdf",keywords:"Secretaría Educación buenas prácticas gestión educativa Montelíbano"},
  {type:"Recurso",title:"Sexualidad",description:"Material histórico asociado al trabajo educativo de la Secretaría de Educación.",href:"../Sexualidad.pdf",keywords:"Secretaría Educación sexualidad formación Montelíbano"},
  {type:"Recurso",title:"Ideograma de la Secretaría de Educación",description:"Representación gráfica conservada en el archivo institucional.",href:"../Secretaria%20de%20Educacion%20-%20Mapa.pdf",keywords:"Secretaría Educación mapa ideograma organización Montelíbano"},
  {type:"Recurso",title:"Plan de Mejoramiento - José María Córdoba, Pica-Pica Nuevo",description:"Evidencia histórica del acompañamiento regional asociado a Fundación San Isidro.",href:"../Plan%20de%20Mejoramiento%20-%202011-Jose%20Maria%20Cordoba%20-%20Pica%20Pica%20Nuevo.pdf",keywords:"Fundación San Isidro plan mejoramiento José María Córdoba Pica Pica Montelíbano"},
  {type:"Recurso",title:"Plan de Mejoramiento - José María Córdoba, Puerto Libertador",description:"Evidencia histórica del acompañamiento regional asociado a Fundación San Isidro.",href:"../Plan%20de%20Mejoramiento%20-%202011-Jose%20Maria%20Cordoba%20-%20Pto%20Libertador.pdf",keywords:"Fundación San Isidro plan mejoramiento José María Córdoba Puerto Libertador"},
  {type:"Recurso",title:"Plan de Mejoramiento - La Esperanza, Parcelas de San Javier",description:"Evidencia histórica del acompañamiento regional asociado a Fundación San Isidro.",href:"../Plan%20de%20Mejoramiento%20-%202011-La%20Esperanza%20de%20Parcelas%20de%20San%20javier.pdf",keywords:"Fundación San Isidro plan mejoramiento La Esperanza Parcelas San Javier Montelíbano"},
  {type:"Recurso",title:"Plan de Mejoramiento - Germán Gómez Peláez",description:"Evidencia histórica del acompañamiento regional asociado a Fundación San Isidro.",href:"../Plan%20de%20Mejoramiento%20-%202011%20-%20German%20Gomez%20Pelaez.pdf",keywords:"Fundación San Isidro plan mejoramiento Germán Gómez Peláez Puerto Libertador"},
  {type:"Recurso",title:"Plan de Mejoramiento - Sitio Nuevo, La Apartada",description:"Evidencia histórica del acompañamiento regional asociado a Fundación San Isidro.",href:"../Plan%20de%20Mejoramiento%20-%202011-Sitio%20Nuevo%20-%20La%20Apartada.pdf",keywords:"Fundación San Isidro plan mejoramiento Sitio Nuevo La Apartada"}
);
